app:
  name: SettlementService
  description: SettlementService
  version: 1.0.0


server:
  port : 8080

logging:
  file:
    name: salary-management-service.log
  level:
    root: INFO

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: SalaryManagementService
  datasource:
    platform: h2
    initialization-mode: always
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:salarydb
    username: sa
    password:

  jpa:
    hibernate:
    ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  flyway:
    baselineOnMigrate: true
    check-location: true
    locations: classpath:db/migration
    url: jdbc:h2:mem:salarydb
    schemas: salarydb
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html